# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  apiServer: 'http://serveur1.arras-sio.com'
  apiAdress: 'http://serveur1.arras-sio.com/symfony4-4149/API/public/api/'
  apiUrl: 'symfony4-4149/API/public/api/'
 

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
artgris_file_manager:
    conf:
        files:
          dir: "../uploads/images"
          type: 'file'
        images:
          dir: "../uploads/images"
          type: 'image'
          view: thumbnail
        button:
           dir: "../uploads/images"

fos_ck_editor:
    default_config: base
    configs:
        base:
            
            filebrowserBrowseRoute: file_manager
            filebrowserBrowseRouteParameters:
                conf: files
                module: ckeditor
            filebrowserImageBrowseRoute: file_manager
            filebrowserImageBrowseRouteParameters:
                conf: images
                module: ckeditor
        image:
            removePlugins: "wordcount"
            toolbar: "toolbar_image"
            filebrowserBrowseRoute: file_manager
            filebrowserBrowseRouteParameters:
                conf: files
                module: ckeditor
            filebrowserImageBrowseRoute: file_manager
            filebrowserImageBrowseRouteParameters:
                conf: images
                module: ckeditor
        commentaires:
            toolbar: [ ["Bold", "-", "Italic", "-", "Underline"] ]
           
    toolbars:
      configs:
        toolbar_image: ["@document"]
      items:
        document: ["Image"]
        links: ["Image"]
        